#!/bin/bash
if [[ "$1" == 'debug'  ]]; then set -x;		_DEBUG=$1; shift; fi
if [[ "$1" == 'debug2' ]]; then set -xvT;	_DEBUG=$1; shift; fi
if [[ "$1" == 'trace'  ]]; then 		_TRACE=$1; shift; fi
####################################################################
# - CleanDB -
# Module WatchLG
#-------------------------
REALPATH=`realpath $0`
WHERE=`dirname $REALPATH`
ME=`basename $REALPATH`
cd $WHERE
. ../../system.conf
. ../../watchermap.conf
. ../../common.conf
. ../../common.bashlib
#-------------------------
. WatchLG.conf

#
# Strip junk from database ...
#
del_IP() {
	echo "Deleting IP: $1 from $DB"
	$SQL "delete from $TABLE where IP='$1';"
}

echo "Cleaning-up database $WHERE/$DB ... please wait ..."

#
# Remove junk IP addresses that break the load process badly
#
BANDITS=`$SQL "select IP from $TABLE;"`

for b in `echo $BANDITS`
do
	validate_IP $b
	if [ $? -ne 0 ]
	then 
		echo "Junk IP: $b "
		del_IP "$b"
	fi
done

